import type { ApiCommandFixture } from '../types/cli-test';

export const API_COMMAND_FIXTURES: ReadonlyArray<ApiCommandFixture> = [
  { command: 'posts create', path: '/v1/posts', method: 'POST', args: ['--title', 'Ship notes', '--content-type', 'blog_post', '--slug', 'ship-notes', '--markdown', '# Shipped'], body: { title: 'Ship notes', contentType: 'blog_post', slug: 'ship-notes', markdown: '# Shipped', status: 'draft' } },
  { command: 'posts schedule', path: '/v1/posts/post_1/schedule', method: 'POST', args: ['post_1', '--scheduled-at', '2027-01-01T08:00:00Z', '--time-zone', 'Europe/Berlin'], body: { scheduledAt: '2027-01-01T08:00:00Z', timeZone: 'Europe/Berlin', destinations: [] } },
  { command: 'posts schedule-get', path: '/v1/posts/post_1/schedule', args: ['post_1'] },
  { command: 'posts schedule-cancel', path: '/v1/posts/post_1/schedule', method: 'DELETE', args: ['post_1'] },
  { command: 'webhooks endpoints list', path: '/v1/webhooks' },
  { command: 'webhooks endpoints create', path: '/v1/webhooks', method: 'POST', args: ['--url', 'https://example.com/hooks', '--events', 'post.created', '--events', 'post.published'], body: { url: 'https://example.com/hooks', events: ['post.created', 'post.published'] } },
  { command: 'webhooks endpoints delete', path: '/v1/webhooks/endpoint_1', method: 'DELETE', args: ['endpoint_1'] },
  { command: 'webhooks deliveries list', path: '/v1/webhooks/deliveries', args: ['--offset', '25', '--status', 'failed'], query: { offset: '25', status: 'failed' } },
  { command: 'webhooks deliveries get', path: '/v1/webhooks/deliveries/delivery_1', args: ['delivery_1'] },
  { command: 'webhooks deliveries retry', path: '/v1/webhooks/deliveries/delivery_1/retry', method: 'POST', args: ['delivery_1'] },
  { command: 'event-triggers list', path: '/v1/event-triggers', args: ['--repository-ids', 'repo_1'], query: { repositoryIds: 'repo_1' } },
  { command: 'event-triggers get', path: '/v1/event-triggers/trigger_1', args: ['trigger_1'] },
  { command: 'event-triggers create', path: '/v1/event-triggers', method: 'POST', args: ['--source-type', 'github_webhook', '--source-config', '{"eventTypes":["release"]}', '--targets', '{"repositoryIds":["repo_1"]}', '--output-type', 'changelog', '--enabled'], body: { sourceType: 'github_webhook', sourceConfig: { eventTypes: ['release'], includePreReleases: true, ignoreCommitPatterns: [] }, targets: { repositoryIds: ['repo_1'] }, outputType: 'changelog', enabled: true, autoPublish: false } },
  { command: 'event-triggers update', path: '/v1/event-triggers/trigger_1', method: 'PATCH', args: ['trigger_1', '--source-type', 'github_webhook', '--source-config', '{"eventTypes":["push"]}', '--targets', '{"repositoryIds":["repo_1"]}', '--output-type', 'blog_post', '--no-enabled'], body: { sourceType: 'github_webhook', sourceConfig: { eventTypes: ['push'], includePreReleases: true, ignoreCommitPatterns: [] }, targets: { repositoryIds: ['repo_1'] }, outputType: 'blog_post', enabled: false, autoPublish: false } },
  { command: 'event-triggers delete', path: '/v1/event-triggers/trigger_1', method: 'DELETE', args: ['trigger_1'] },
  { command: 'chats list', path: '/v1/chats' },
  { command: 'chats get', path: '/v1/chats/chat%2Fwith%20space', args: ['chat/with space'] },
  { command: 'chats external', path: '/v1/chats/by-external', args: ['--source', 'slack', '--id', 'channel_1'], query: { source: 'slack', id: 'channel_1' } },
  { command: 'chats create', path: '/v1/chats', method: 'POST', args: ['--message', 'What shipped?', '--no-enable-thinking'], body: { message: 'What shipped?', enableThinking: false }, chat: true },
  { command: 'chats message', path: '/v1/chats/chat_1', method: 'POST', args: ['chat_1', '--message', 'Continue'], body: { message: 'Continue' }, chat: true },
  { command: 'skills list', path: '/v1/skills' },
  { command: 'skills get', path: '/v1/skills/humanizer', args: ['humanizer'] },
  { command: 'skills create', path: '/v1/skills', method: 'POST', args: ['--name', 'humanizer', '--description', 'Write naturally', '--content', '# Instructions'], body: { name: 'humanizer', description: 'Write naturally', content: '# Instructions' } },
  { command: 'skills update', path: '/v1/skills/humanizer', method: 'PATCH', args: ['humanizer', '--new-name', 'natural-writing', '--description', 'New description'], body: { name: 'natural-writing', description: 'New description' } },
  { command: 'skills delete', path: '/v1/skills/humanizer', method: 'DELETE', args: ['humanizer'] },
  { command: 'feedback list', path: '/v1/feedback', args: ['--status', 'new', '--kind', 'bug', '--project-id', 'project_1', '--limit', '20', '--page', '2'], query: { status: 'new', kind: 'bug', projectId: 'project_1', limit: '20', page: '2' } },
  { command: 'feedback get', path: '/v1/feedback/feedback_1', args: ['feedback_1'] },
  { command: 'feedback update', path: '/v1/feedback/feedback_1', method: 'PATCH', args: ['feedback_1', '--status', 'resolved'], body: { status: 'resolved' } },
  { command: 'feedback submit', path: '/v1/feedback', method: 'POST', args: ['--message', 'Found a bug', '--kind', 'bug'], body: { message: 'Found a bug', kind: 'bug', source: 'api' } },
  { command: 'feedback submit-public', path: '/v1/feedback/acme', method: 'POST', args: ['acme', '--message', 'Found a bug'], body: { message: 'Found a bug', source: 'api' } },
  { command: 'workspaces list', path: '/v1/me/workspaces', query: { includePending: 'true' } },
  { command: 'whoami', path: '/v1/me/workspaces' },
  { command: 'agents list', path: '/v2/agent-chats', args: ['--limit', '5'], query: { limit: '5' } },
  { command: 'agents create', path: '/v2/eve/v1/session', method: 'POST', args: ['--message', 'Research this'], body: { message: 'Research this' } },
  { command: 'agents message', path: '/v2/eve/v1/session/session_1', method: 'POST', args: ['session_1', '--message', 'Continue'], body: { message: 'Continue' } },
  { command: 'agents events', path: '/v2/eve/v1/session/session_1/stream', args: ['session_1', '--start-index', '7'], query: { startIndex: '7' }, stream: true },
  { command: 'geo changes', path: '/v1/projects/project_1/geo/changes', args: ['project_1'] },
  { command: 'geo prompts history', path: '/v1/projects/project_1/geo/prompts/prompt_1/history', args: ['project_1', 'prompt_1', '--scan-id', 'scan_1'], query: { scanId: 'scan_1' } },
  { command: 'geo sentiment get', path: '/v1/projects/project_1/geo/sentiment', args: ['project_1', '--days', '30'], query: { days: '30' } },
  { command: 'geo sentiment analysis', path: '/v1/projects/project_1/geo/sentiment/analysis', args: ['project_1', '--from', '2026-09-01', '--to', '2026-09-30'], query: { from: '2026-09-01', to: '2026-09-30' } },
  { command: 'geo sentiment evidence', path: '/v1/projects/project_1/geo/sentiment/evidence', args: ['project_1', '--cursor', 'abc'], query: { cursor: 'abc' } },
  { command: 'geo shelf list', path: '/v1/projects/project_1/geo/shelf-sources', args: ['project_1', '--offset', '5', '--limit', '10'], query: { offset: '5', limit: '10' } },
  { command: 'geo visibility prompt-summaries', path: '/v1/projects/project_1/geo/visibility/prompt-results/summaries', args: ['project_1', '--limit', '10', '--engine', 'openai', '--mentioned', 'false', '--cursor', '20', '--query', 'best tools'], query: { limit: '10', engine: 'openai', mentioned: 'false', cursor: '20', query: 'best tools' } },
  { command: 'geo visibility prompt-detail', path: '/v1/projects/project_1/geo/visibility/prompt-results/check%2F1', args: ['project_1', 'check/1'] },
];

export const POST_GENERATION_RESPONSE = {
  organization: { id: 'org_1', name: 'Acme', slug: 'acme', logo: null },
  job: {
    id: 'job_1', organizationId: 'org_1', status: 'queued', contentType: 'changelog',
    lookbackWindow: 'last_7_days', repositoryIds: ['repo_1'], brandVoiceId: null,
    workflowRunId: null, postId: null, error: null, source: 'api',
    createdAt: '2026-10-08T08:00:00Z', updatedAt: '2026-10-08T08:00:00Z', completedAt: null,
  },
};
