export const AUTH_POLL_INTERVAL_MS = 2000;
export const AUTH_POLL_TIMEOUT_MS = 5 * 60 * 1000;
export const AUTH_SESSION_INITIALIZE_TIMEOUT_MS = 10_000;
export const AUTH_VERIFICATION_CODE_BYTES = 4;
export const AUTH_VERIFICATION_CODE_PATTERN = /^[A-F0-9]{4}-[A-F0-9]{4}$/;
