export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Portuguese',
  'Dutch',
  'Italian',
  'Japanese',
  'Korean',
  'Chinese',
  'Arabic',
  'Hindi',
  'Russian',
  'Turkish',
  'Polish',
  'Swedish',
  'Danish',
  'Norwegian',
  'Finnish',
  'Czech',
  'Romanian',
  'Hungarian',
  'Greek',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Ukrainian',
  'Hebrew',
] as const;
export const TONE_PROFILES = ['Conversational', 'Professional', 'Casual', 'Formal'] as const;
