import type { OpenApiOperation } from '../types/openapi';

// Generated by `bun run openapi:sync`; do not edit by hand.
export const OPENAPI_OPERATIONS = [
  {
    "id": "approveGeoContentBrief",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/briefs/{briefId}/approve",
    "summary": "Approve a brief and start the writer",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "briefId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "createAgentSession",
    "method": "POST",
    "path": "/v2/eve/v1/session",
    "summary": "Start a durable agent session",
    "tag": "Agent",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createBrandIdentity",
    "method": "POST",
    "path": "/v1/brand-identities/generate",
    "summary": "Queue async brand identity generation",
    "tag": "Content",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createChat",
    "method": "POST",
    "path": "/v1/chats",
    "summary": "Start a new chat and stream the reply",
    "tag": "Chats",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createEventTrigger",
    "method": "POST",
    "path": "/v1/event-triggers",
    "summary": "Create an event trigger",
    "tag": "Event Triggers",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createGeoPrompt",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/prompts",
    "summary": "Track a new GEO prompt",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "createGeoScan",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/scans",
    "summary": "Trigger a GEO scan",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "createGeoSequence",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/sequences",
    "summary": "Create a GEO prompt sequence",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "createGitHubIntegration",
    "method": "POST",
    "path": "/v1/integrations/github",
    "summary": "Create a GitHub integration",
    "tag": "Content",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createPost",
    "method": "POST",
    "path": "/v1/posts",
    "summary": "Create a post",
    "tag": "Content",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createPostGeneration",
    "method": "POST",
    "path": "/v1/posts/generate",
    "summary": "Queue async post generation",
    "tag": "Content",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createProject",
    "method": "POST",
    "path": "/v1/projects",
    "summary": "Create a GEO project",
    "tag": "GEO",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createSchedule",
    "method": "POST",
    "path": "/v1/schedules",
    "summary": "Create a schedule",
    "tag": "Schedules",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "createSkill",
    "method": "POST",
    "path": "/v1/skills",
    "summary": "Create a skill",
    "tag": "Skills",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "deleteBrandIdentity",
    "method": "DELETE",
    "path": "/v1/brand-identities/{brandIdentityId}",
    "summary": "Delete a single brand identity",
    "tag": "Content",
    "parameters": [
      {
        "name": "brandIdentityId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteEventTrigger",
    "method": "DELETE",
    "path": "/v1/event-triggers/{triggerId}",
    "summary": "Delete an event trigger",
    "tag": "Event Triggers",
    "parameters": [
      {
        "name": "triggerId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteGeoCompetitor",
    "method": "DELETE",
    "path": "/v1/projects/{projectId}/geo/competitors/{name}",
    "summary": "Stop tracking a GEO competitor",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "name",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteGeoPrompt",
    "method": "DELETE",
    "path": "/v1/projects/{projectId}/geo/prompts/{promptId}",
    "summary": "Stop tracking a GEO prompt",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "promptId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteGeoSequence",
    "method": "DELETE",
    "path": "/v1/projects/{projectId}/geo/sequences/{sequenceId}",
    "summary": "Delete a GEO prompt sequence",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "sequenceId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteIntegration",
    "method": "DELETE",
    "path": "/v1/integrations/{integrationId}",
    "summary": "Delete a single integration",
    "tag": "Content",
    "parameters": [
      {
        "name": "integrationId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deletePost",
    "method": "DELETE",
    "path": "/v1/posts/{postId}",
    "summary": "Delete a single post",
    "tag": "Content",
    "parameters": [
      {
        "name": "postId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteProject",
    "method": "DELETE",
    "path": "/v1/projects/{projectId}",
    "summary": "Delete a GEO project and all of its GEO data",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteSchedule",
    "method": "DELETE",
    "path": "/v1/schedules/{scheduleId}",
    "summary": "Delete a schedule",
    "tag": "Schedules",
    "parameters": [
      {
        "name": "scheduleId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "deleteSkill",
    "method": "DELETE",
    "path": "/v1/skills/{name}",
    "summary": "Delete a skill",
    "tag": "Skills",
    "parameters": [
      {
        "name": "name",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getBrandIdentity",
    "method": "GET",
    "path": "/v1/brand-identities/{brandIdentityId}",
    "summary": "Get a single brand identity",
    "tag": "Content",
    "parameters": [
      {
        "name": "brandIdentityId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getBrandIdentityGeneration",
    "method": "GET",
    "path": "/v1/brand-identities/generate/{jobId}",
    "summary": "Get async brand identity generation status",
    "tag": "Content",
    "parameters": [
      {
        "name": "jobId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getChat",
    "method": "GET",
    "path": "/v1/chats/{chatId}",
    "summary": "Get a single chat with messages",
    "tag": "Chats",
    "parameters": [
      {
        "name": "chatId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getChatByExternalChannel",
    "method": "GET",
    "path": "/v1/chats/by-external",
    "summary": "Get a chat by external channel id",
    "tag": "Chats",
    "parameters": [
      {
        "name": "source",
        "in": "query",
        "required": true
      },
      {
        "name": "id",
        "in": "query",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getEventTrigger",
    "method": "GET",
    "path": "/v1/event-triggers/{triggerId}",
    "summary": "Get an event trigger",
    "tag": "Event Triggers",
    "parameters": [
      {
        "name": "triggerId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getFeedback",
    "method": "GET",
    "path": "/v1/feedback/{feedbackId}",
    "summary": "Get a single feedback entry",
    "tag": "Feedback",
    "parameters": [
      {
        "name": "feedbackId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoAgentReadiness",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/agent-readiness",
    "summary": "Get the latest agent readiness report",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoContentBrief",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/briefs/{briefId}",
    "summary": "Get a single content brief",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "briefId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoIngestSetup",
    "method": "GET",
    "path": "/v1/geo/ingest/setup",
    "summary": "Get the install snippets",
    "tag": "GEO",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "getGeoPromptHistory",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/prompts/{promptId}/history",
    "summary": "Get the stored check history for one prompt",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "promptId",
        "in": "path",
        "required": true
      },
      {
        "name": "scanId",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoPromptResultDetail",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/prompt-results/{checkId}",
    "summary": "Get one full prompt result",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "checkId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoScan",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/scans/{scanId}",
    "summary": "Get a single GEO scan",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "scanId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoSentiment",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/sentiment",
    "summary": "Get aggregate GEO sentiment",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoSentimentAnalysis",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/sentiment/analysis",
    "summary": "Get the stored GEO sentiment analysis",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoSettings",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/settings",
    "summary": "Get a project's GEO settings",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoTrafficJourney",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/traffic/journeys/{journeyId}",
    "summary": "Get one journey's events",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "journeyId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoTrafficLog",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/traffic/log",
    "summary": "Get recent AI traffic events",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "visitorTypes",
        "in": "query",
        "required": false
      },
      {
        "name": "categories",
        "in": "query",
        "required": false
      },
      {
        "name": "host",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoTrafficOverview",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/traffic/overview",
    "summary": "Get AI traffic totals and sources",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityCompetitorDetail",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/competitors/{brand}",
    "summary": "Get one competitor's mention history",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "brand",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityCompetitorShare",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/competitor-share",
    "summary": "Get share of voice across tracked brands",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityLanguageShare",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/language-share",
    "summary": "Get mention rates per tracked language",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityOverview",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/overview",
    "summary": "Get mention rates per engine",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityPromptResults",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/prompt-results",
    "summary": "Get the latest answer per prompt and engine",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getGeoVisibilityTimeseries",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/timeseries",
    "summary": "Get daily mention counts per engine",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "getPost",
    "method": "GET",
    "path": "/v1/posts/{postId}",
    "summary": "Get a single post",
    "tag": "Content",
    "parameters": [
      {
        "name": "postId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getPostGeneration",
    "method": "GET",
    "path": "/v1/posts/generate/{jobId}",
    "summary": "Get async post generation status",
    "tag": "Content",
    "parameters": [
      {
        "name": "jobId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getProject",
    "method": "GET",
    "path": "/v1/projects/{projectId}",
    "summary": "Get a single GEO project",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getPublicApiStatus",
    "method": "GET",
    "path": "/v1/status",
    "summary": "Check public API reachability",
    "tag": "Discovery",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "getSkill",
    "method": "GET",
    "path": "/v1/skills/{name}",
    "summary": "Get a single skill",
    "tag": "Skills",
    "parameters": [
      {
        "name": "name",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "getWorkspaces",
    "method": "GET",
    "path": "/v1/me/workspaces",
    "summary": "Get authenticated workspace context",
    "tag": "Discovery",
    "parameters": [
      {
        "name": "includePending",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "importGeoCompetitors",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/competitors/import",
    "summary": "Bulk import GEO competitors",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "importGeoPrompts",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/prompts/import",
    "summary": "Bulk import GEO prompts",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "issueGeoIngestToken",
    "method": "POST",
    "path": "/v1/geo/ingest/token",
    "summary": "Issue the tracking token",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listAgentChats",
    "method": "GET",
    "path": "/v2/agent-chats",
    "summary": "List agent sessions",
    "tag": "Agent",
    "parameters": [
      {
        "name": "limit",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listBrandIdentities",
    "method": "GET",
    "path": "/v1/brand-identities",
    "summary": "List available brand identities",
    "tag": "Content",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "listChats",
    "method": "GET",
    "path": "/v1/chats",
    "summary": "List chats",
    "tag": "Chats",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "listEventTriggers",
    "method": "GET",
    "path": "/v1/event-triggers",
    "summary": "List event triggers",
    "tag": "Event Triggers",
    "parameters": [
      {
        "name": "repositoryIds",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listFeedback",
    "method": "GET",
    "path": "/v1/feedback",
    "summary": "List feedback",
    "tag": "Feedback",
    "parameters": [
      {
        "name": "status",
        "in": "query",
        "required": false
      },
      {
        "name": "kind",
        "in": "query",
        "required": false
      },
      {
        "name": "projectId",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "page",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoChanges",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/changes",
    "summary": "Compare the two latest GEO scans",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoCompetitors",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/competitors",
    "summary": "List tracked GEO competitors",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoContentBriefs",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/briefs",
    "summary": "List content briefs",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoContentGaps",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/gaps",
    "summary": "List content gaps",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoPromptResultSummaries",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/visibility/prompt-results/summaries",
    "summary": "List compact prompt result summaries",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "engine",
        "in": "query",
        "required": false
      },
      {
        "name": "mentioned",
        "in": "query",
        "required": false
      },
      {
        "name": "query",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoPrompts",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/prompts",
    "summary": "List tracked GEO prompts",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoScans",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/scans",
    "summary": "List GEO scans",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "page",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoSentimentEvidence",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/sentiment/evidence",
    "summary": "List answers used as sentiment evidence",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoSequences",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/sequences",
    "summary": "List GEO prompt sequences",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoShelfSources",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/shelf-sources",
    "summary": "List stored GEO shelf sources",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "offset",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoTrafficJourneys",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/traffic/journeys",
    "summary": "List AI traffic journeys",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listGeoTrafficPages",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/traffic/pages",
    "summary": "List the most visited pages",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "days",
        "in": "query",
        "required": false
      },
      {
        "name": "from",
        "in": "query",
        "required": false
      },
      {
        "name": "to",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "visitorType",
        "in": "query",
        "required": false
      },
      {
        "name": "host",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listIntegrations",
    "method": "GET",
    "path": "/v1/integrations",
    "summary": "List available integrations",
    "tag": "Content",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "listPosts",
    "method": "GET",
    "path": "/v1/posts",
    "summary": "List posts",
    "tag": "Content",
    "parameters": [
      {
        "name": "sort",
        "in": "query",
        "required": false
      },
      {
        "name": "limit",
        "in": "query",
        "required": false
      },
      {
        "name": "page",
        "in": "query",
        "required": false
      },
      {
        "name": "status",
        "in": "query",
        "required": false
      },
      {
        "name": "contentType",
        "in": "query",
        "required": false
      },
      {
        "name": "brandIdentityId",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listProjects",
    "method": "GET",
    "path": "/v1/projects",
    "summary": "List GEO projects",
    "tag": "GEO",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "listSchedules",
    "method": "GET",
    "path": "/v1/schedules",
    "summary": "List schedules",
    "tag": "Schedules",
    "parameters": [
      {
        "name": "repositoryIds",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "listSkills",
    "method": "GET",
    "path": "/v1/skills",
    "summary": "List skills",
    "tag": "Skills",
    "parameters": [],
    "hasBody": false
  },
  {
    "id": "patchSkill",
    "method": "PATCH",
    "path": "/v1/skills/{name}",
    "summary": "Update a skill",
    "tag": "Skills",
    "parameters": [
      {
        "name": "name",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "planGeoContentBrief",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/briefs",
    "summary": "Plan a content brief",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "postChatMessage",
    "method": "POST",
    "path": "/v1/chats/{chatId}",
    "summary": "Post a message to an existing chat and stream the reply",
    "tag": "Chats",
    "parameters": [
      {
        "name": "chatId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "rotateGeoIngestToken",
    "method": "POST",
    "path": "/v1/geo/ingest/rotate-token",
    "summary": "Rotate the tracking token",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "query",
        "required": false
      }
    ],
    "hasBody": false
  },
  {
    "id": "runGeoSequence",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/sequences/{sequenceId}/run",
    "summary": "Run a GEO prompt sequence now",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "sequenceId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "sendAgentSessionMessage",
    "method": "POST",
    "path": "/v2/eve/v1/session/{sessionId}",
    "summary": "Send a follow-up message or answer a pending input request",
    "tag": "Agent",
    "parameters": [
      {
        "name": "sessionId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "startGeoAgentReadinessScan",
    "method": "POST",
    "path": "/v1/projects/{projectId}/geo/agent-readiness/scan",
    "summary": "Start an agent readiness scan",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "streamAgentSessionEvents",
    "method": "GET",
    "path": "/v2/eve/v1/session/{sessionId}/stream",
    "summary": "Stream an agent session's events",
    "tag": "Agent",
    "parameters": [
      {
        "name": "sessionId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "submitFeedback",
    "method": "POST",
    "path": "/v1/feedback",
    "summary": "Submit feedback with an API key",
    "tag": "Feedback",
    "parameters": [],
    "hasBody": true
  },
  {
    "id": "submitOrganizationFeedback",
    "method": "POST",
    "path": "/v1/feedback/{organizationSlug}",
    "summary": "Submit feedback to an organization's feedback URL",
    "tag": "Feedback",
    "parameters": [
      {
        "name": "organizationSlug",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "suggestGeoCompetitors",
    "method": "GET",
    "path": "/v1/projects/{projectId}/geo/competitors/suggestions",
    "summary": "Suggest GEO competitors for a domain",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "domain",
        "in": "query",
        "required": true
      }
    ],
    "hasBody": false
  },
  {
    "id": "updateBrandIdentity",
    "method": "PATCH",
    "path": "/v1/brand-identities/{brandIdentityId}",
    "summary": "Update a single brand identity",
    "tag": "Content",
    "parameters": [
      {
        "name": "brandIdentityId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateEventTrigger",
    "method": "PATCH",
    "path": "/v1/event-triggers/{triggerId}",
    "summary": "Update an event trigger",
    "tag": "Event Triggers",
    "parameters": [
      {
        "name": "triggerId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateFeedback",
    "method": "PATCH",
    "path": "/v1/feedback/{feedbackId}",
    "summary": "Update feedback status",
    "tag": "Feedback",
    "parameters": [
      {
        "name": "feedbackId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateGeoPrompt",
    "method": "PATCH",
    "path": "/v1/projects/{projectId}/geo/prompts/{promptId}",
    "summary": "Update a tracked GEO prompt",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "promptId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateGeoSequence",
    "method": "PATCH",
    "path": "/v1/projects/{projectId}/geo/sequences/{sequenceId}",
    "summary": "Update a GEO prompt sequence",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      },
      {
        "name": "sequenceId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateGeoSettings",
    "method": "PATCH",
    "path": "/v1/projects/{projectId}/geo/settings",
    "summary": "Replace a project's GEO settings",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updatePost",
    "method": "PATCH",
    "path": "/v1/posts/{postId}",
    "summary": "Update a single post",
    "tag": "Content",
    "parameters": [
      {
        "name": "postId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateProject",
    "method": "PATCH",
    "path": "/v1/projects/{projectId}",
    "summary": "Rename a GEO project or relink its brand identity",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "updateSchedule",
    "method": "PATCH",
    "path": "/v1/schedules/{scheduleId}",
    "summary": "Update a schedule",
    "tag": "Schedules",
    "parameters": [
      {
        "name": "scheduleId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  },
  {
    "id": "upsertGeoCompetitor",
    "method": "PUT",
    "path": "/v1/projects/{projectId}/geo/competitors",
    "summary": "Create or update a tracked GEO competitor",
    "tag": "GEO",
    "parameters": [
      {
        "name": "projectId",
        "in": "path",
        "required": true
      }
    ],
    "hasBody": true
  }
] as const satisfies ReadonlyArray<OpenApiOperation>;
