import { buildOpenApiCatalog } from '../src/utils/openapi-catalog';
import { writeTextFileAtomically } from '../src/utils/files';

const source = process.argv[2] ?? "https://api.usenotra.com/openapi.json";
const target = new URL("../src/constants/openapi.ts", import.meta.url);
const document: unknown = /^https?:\/\//.test(source)
  ? await fetch(source).then((response) => {
      if (!response.ok) throw new Error(`Could not fetch ${source}: HTTP ${response.status}`);
      return response.json();
    })
  : await Bun.file(source).json();
const { operations, requests } = buildOpenApiCatalog(document);

const contents = [
  "import type { OpenApiOperation } from '../types/openapi';",
  "import type { OperationRequestSchema } from '../types/api-command';",
  "",
  "// Generated by `bun run openapi:sync`; do not edit by hand.",
  `export const OPENAPI_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const satisfies ReadonlyArray<OpenApiOperation>;`,
  "",
  `export const OPENAPI_REQUEST_SCHEMAS: Record<string, OperationRequestSchema> = ${JSON.stringify(requests, null, 2)};`,
  '',
].join("\n");

await writeTextFileAtomically(target, contents);
console.log(`Wrote ${operations.length} operations to ${target.pathname}.`);
